# Generated by Django 5.2.13 on 2026-04-23 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_seed_default_categories'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expense',
            new_name='accounting__monthly_add847_idx',
            old_name='accounting__monthly_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='monthlyaccounting',
            new_name='accounting__year_c161a1_idx',
            old_name='accounting__year_month_idx',
        ),
    ]
