# Generated by Django 5.2.8 on 2025-12-01 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('barcode', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Barcode')),
                ('price_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price HT')),
                ('tva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='VAT (%)')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('min_stock', models.IntegerField(default=5, verbose_name='Min Stock')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'indexes': [models.Index(fields=['name'], name='inventory_p_name_f6a6a1_idx'), models.Index(fields=['barcode'], name='inventory_p_barcode_3a77e5_idx')],
            },
        ),
    ]
