# Generated by Django 5.2.8 on 2025-12-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='suppliers/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price_ht',
            field=models.DecimalField(decimal_places=2, help_text='Selling price before tax', max_digits=10, verbose_name='Sale Price HT'),
        ),
    ]
