# Generated by Django 5.2.8 on 2025-12-12 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_supplier_image_alter_product_sale_price_ht'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Old Purchase Price')),
                ('new_purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='New Purchase Price')),
                ('old_sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Old Sale Price')),
                ('new_sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='New Sale Price')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
