# Generated by Codex on 2026-04-26

import django.db.models.deletion
from django.db import migrations, models


def seed_existing_cost_layers(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    ProductCostLayer = apps.get_model('inventory', 'ProductCostLayer')

    layers = []
    for product in Product.objects.filter(stock__gt=0):
        layers.append(ProductCostLayer(
            product_id=product.id,
            unit_cost=product.purchase_price,
            initial_quantity=product.stock,
            remaining_quantity=product.stock,
            note='Stock existant avant FIFO',
        ))
    ProductCostLayer.objects.bulk_create(layers, batch_size=500)


def unseed_existing_cost_layers(apps, schema_editor):
    ProductCostLayer = apps.get_model('inventory', 'ProductCostLayer')
    ProductCostLayer.objects.filter(note='Stock existant avant FIFO').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorycount_purchaseorder_purchaseorderitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCostLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Cost')),
                ('initial_quantity', models.PositiveIntegerField(verbose_name='Initial Quantity')),
                ('remaining_quantity', models.PositiveIntegerField(verbose_name='Remaining Quantity')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_layers', to='inventory.product')),
                ('source_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_layer', to='inventory.stockmovement')),
            ],
            options={
                'verbose_name': 'Product Cost Layer',
                'verbose_name_plural': 'Product Cost Layers',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='productcostlayer',
            index=models.Index(fields=['product', 'remaining_quantity', 'created_at'], name='inventory_p_product_aba1b1_idx'),
        ),
        migrations.RunPython(seed_existing_cost_layers, unseed_existing_cost_layers),
    ]
