# Generated by Django 5.2.14 on 2026-07-20 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, Q


def normalize_inventory_data(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    ProductCostLayer = apps.get_model('inventory', 'ProductCostLayer')
    StockMovement = apps.get_model('inventory', 'StockMovement')
    PriceHistory = apps.get_model('inventory', 'PriceHistory')
    PurchaseOrderItem = apps.get_model('inventory', 'PurchaseOrderItem')
    InventoryCountItem = apps.get_model('inventory', 'InventoryCountItem')

    invalid_products = Product.objects.filter(
        Q(purchase_price__lt=0)
        | Q(sale_price_ht__lt=0)
        | Q(tva__lt=0)
        | Q(tva__gt=100)
        | Q(stock__lt=0)
        | Q(min_stock__lt=0)
    )
    for product in invalid_products.iterator():
        old_purchase = product.purchase_price
        old_sale = product.sale_price_ht
        old_stock = product.stock
        product.purchase_price = max(product.purchase_price, 0)
        product.sale_price_ht = max(product.sale_price_ht, 0)
        product.tva = min(max(product.tva, 0), 100)
        product.stock = max(product.stock, 0)
        product.min_stock = max(product.min_stock, 0)
        product.save(update_fields=[
            'purchase_price', 'sale_price_ht', 'tva', 'stock', 'min_stock',
        ])
        if old_purchase != product.purchase_price or old_sale != product.sale_price_ht:
            PriceHistory.objects.create(
                product_id=product.pk,
                old_purchase_price=old_purchase,
                new_purchase_price=product.purchase_price,
                old_sale_price=old_sale,
                new_sale_price=product.sale_price_ht,
                reason='Normalisation avant contraintes inventaire',
            )
        if old_stock < 0:
            StockMovement.objects.create(
                product_id=product.pk,
                movement_type='ADJUST',
                quantity=-old_stock,
                stock_before=old_stock,
                stock_after=0,
                notes='Correction migration d’un stock négatif hérité',
            )
            ProductCostLayer.objects.filter(product_id=product.pk).update(
                remaining_quantity=0
            )

    for layer in ProductCostLayer.objects.all().iterator():
        updates = {}
        if layer.unit_cost < 0:
            updates['unit_cost'] = 0
        if layer.sale_price is not None and layer.sale_price < 0:
            updates['sale_price'] = 0
        if layer.remaining_quantity > layer.initial_quantity:
            updates['initial_quantity'] = layer.remaining_quantity
        if updates:
            ProductCostLayer.objects.filter(pk=layer.pk).update(**updates)

    PurchaseOrderItem.objects.filter(quantity__lte=0).update(quantity=1)
    PurchaseOrderItem.objects.filter(received_quantity__lt=0).update(
        received_quantity=0
    )
    PurchaseOrderItem.objects.filter(unit_cost__lt=0).update(unit_cost=0)
    PurchaseOrderItem.objects.filter(sale_price__lt=0).update(sale_price=0)
    for item in PurchaseOrderItem.objects.filter(
        received_quantity__gt=models.F('quantity')
    ).iterator():
        item.received_quantity = item.quantity
        item.save(update_fields=['received_quantity'])

    duplicate_groups = (
        PurchaseOrderItem.objects.values('order_id', 'product_id')
        .annotate(row_count=Count('id'))
        .filter(row_count__gt=1)
    )
    for group in duplicate_groups.iterator():
        items = list(PurchaseOrderItem.objects.filter(
            order_id=group['order_id'],
            product_id=group['product_id'],
        ).order_by('id'))
        keeper = items[0]
        keeper.quantity = sum(item.quantity for item in items)
        keeper.received_quantity = min(
            keeper.quantity,
            sum(item.received_quantity for item in items),
        )
        keeper.save(update_fields=['quantity', 'received_quantity'])
        PurchaseOrderItem.objects.filter(
            pk__in=[item.pk for item in items[1:]]
        ).delete()

    InventoryCountItem.objects.filter(expected_quantity__lt=0).update(
        expected_quantity=0
    )
    InventoryCountItem.objects.filter(counted_quantity__lt=0).update(
        counted_quantity=0
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_lot_sale_prices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SyncStockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_id', models.UUIDField()),
                ('stock', models.PositiveIntegerField()),
                ('source_updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(
            normalize_inventory_data,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='inventorycountitem',
            constraint=models.CheckConstraint(condition=models.Q(('expected_quantity__gte', 0)), name='inventory_count_expected_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='inventorycountitem',
            constraint=models.CheckConstraint(condition=models.Q(('counted_quantity__isnull', True), ('counted_quantity__gte', 0), _connector='OR'), name='inventory_count_counted_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0)), name='inventory_product_purchase_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price_ht__gte', 0)), name='inventory_product_sale_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('tva__gte', 0), ('tva__lte', 100)), name='inventory_product_tva_range'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='inventory_product_stock_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('min_stock__gte', 0)), name='inventory_product_min_stock_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='productcostlayer',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='inventory_fifo_cost_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='productcostlayer',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__isnull', True), ('sale_price__gte', 0), _connector='OR'), name='inventory_fifo_sale_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='productcostlayer',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_quantity__lte', models.F('initial_quantity'))), name='inventory_fifo_remaining_lte_initial'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='inventory_po_unique_product'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_po_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__gte', 0)), name='inventory_po_received_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__lte', models.F('quantity'))), name='inventory_po_received_lte_quantity'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='inventory_po_cost_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__isnull', True), ('sale_price__gte', 0), _connector='OR'), name='inventory_po_sale_nonneg'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='syncstocksnapshot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_stock_snapshots', to='inventory.product'),
        ),
        migrations.AddConstraint(
            model_name='purchasereceipt',
            constraint=models.UniqueConstraint(fields=('order', 'receipt_id'), name='inventory_receipt_unique_order_key'),
        ),
        migrations.AddIndex(
            model_name='syncstocksnapshot',
            index=models.Index(fields=['product', 'source_updated_at'], name='inv_sync_stock_prod_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncstocksnapshot',
            constraint=models.UniqueConstraint(fields=('origin_id', 'product'), name='inventory_sync_stock_unique_origin_product'),
        ),
    ]
