# Generated by Django 5.2.14 on 2026-07-20 15:15

from django.conf import settings
from django.db import migrations, models


def normalize_movement_prices(apps, schema_editor):
    StockMovement = apps.get_model('inventory', 'StockMovement')
    StockMovement.objects.filter(unit_cost__lt=0).update(unit_cost=0)
    StockMovement.objects.filter(sale_price__lt=0).update(sale_price=0)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_purchasereceipt_syncstocksnapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            normalize_movement_prices,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__isnull', True), ('unit_cost__gte', 0), _connector='OR'), name='inventory_movement_cost_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__isnull', True), ('sale_price__gte', 0), _connector='OR'), name='inventory_movement_sale_nonneg'),
        ),
    ]
