# Generated by Django 5.2.14 on 2026-07-20 20:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_stockmovement_inventory_movement_cost_nonneg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('OTHER', 'Other')], max_length=10, verbose_name='Payment Method')),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='Paid On')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Reference')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('operation_id', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Idempotency Key')),
                ('operation_payload_hash', models.CharField(editable=False, max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVERSED', 'Reversed')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reversed At')),
                ('reversal_reason', models.CharField(blank=True, max_length=255, verbose_name='Reversal Reason')),
                ('reversal_operation_id', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name='Reversal Idempotency Key')),
                ('reversal_payload_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='inventory.purchaseorder', verbose_name='Purchase Order')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments_reversed', to=settings.AUTH_USER_MODEL, verbose_name='Reversed By')),
            ],
            options={
                'verbose_name': 'Supplier Payment',
                'verbose_name_plural': 'Supplier Payments',
                'ordering': ['-paid_on', '-created_at', '-id'],
                'indexes': [models.Index(fields=['order', 'status'], name='inventory_s_order_i_0ea785_idx'), models.Index(fields=['method', 'paid_on', 'status'], name='inventory_s_method_adc503_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='inventory_supplier_payment_amount_pos')],
            },
        ),
    ]
