# Generated by Django 5.2.14 on 2026-07-20 20:18

from decimal import Decimal, InvalidOperation

from django.db import migrations, models


def initialize_received_cost_totals(apps, schema_editor):
    PurchaseOrderItem = apps.get_model('inventory', 'PurchaseOrderItem')
    PurchaseReceipt = apps.get_model('inventory', 'PurchaseReceipt')
    actual_by_item = {}
    quantity_by_item = {}
    for receipt in PurchaseReceipt.objects.all().iterator():
        for result in (receipt.result or {}).get('results', []):
            try:
                item_id = int(result['item_id'])
                quantity = int(result['received'])
                unit_cost = Decimal(str(result['unit_cost_applied']))
            except (KeyError, TypeError, ValueError, InvalidOperation):
                continue
            if quantity <= 0 or unit_cost < 0:
                continue
            actual_by_item[item_id] = (
                actual_by_item.get(item_id, Decimal('0.00'))
                + quantity * unit_cost
            )
            quantity_by_item[item_id] = quantity_by_item.get(item_id, 0) + quantity

    for item in PurchaseOrderItem.objects.filter(received_quantity__gt=0).iterator():
        recorded_quantity = min(
            quantity_by_item.get(item.pk, 0),
            item.received_quantity,
        )
        missing_quantity = item.received_quantity - recorded_quantity
        item.received_cost_total = (
            actual_by_item.get(item.pk, Decimal('0.00'))
            + missing_quantity * item.unit_cost
        )
        item.save(update_fields=['received_cost_total'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_supplier_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='received_cost_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumulated supplier cost actually applied on received units', max_digits=14, verbose_name='Actual Received Cost Total'),
        ),
        migrations.RunPython(
            initialize_received_cost_totals,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('received_cost_total__gte', 0)), name='inventory_po_received_cost_nonneg'),
        ),
    ]
