# Generated by Django 5.2.8 on 2025-12-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_discount_return_returnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='synced',
            field=models.BooleanField(default=False, verbose_name='Synced to cloud'),
        ),
        migrations.AddField(
            model_name='sale',
            name='synced',
            field=models.BooleanField(default=False, verbose_name='Synced to cloud'),
        ),
        migrations.AddField(
            model_name='sale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
