from django.db import migrations, models


class Migration(migrations.Migration):
    """
    S-18: Add local_id to Sale and Return for idempotent sync deduplication.

    Previously, _import_sale() deduplicated by matching created_at timestamps,
    which could produce false positives (two sales at the exact same millisecond)
    or false negatives (timezone edge cases). local_id is the authoritative key
    generated by the local POS server; cloud import now checks this field first.
    """

    dependencies = [
        ('sales', '0003_return_synced_sale_synced_sale_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='local_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Unique ID from the local POS used to prevent duplicate imports during sync.',
                max_length=100,
                null=True,
                verbose_name='Local ID',
            ),
        ),
        migrations.AddField(
            model_name='return',
            name='local_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name='Local ID',
            ),
        ),
    ]
