# Generated by Codex on 2026-04-26

from decimal import Decimal

from django.db import migrations, models


def seed_sale_item_costs(apps, schema_editor):
    SaleItem = apps.get_model('sales', 'SaleItem')

    for item in SaleItem.objects.select_related('product').all().iterator():
        purchase_price = item.product.purchase_price if item.product_id else Decimal('0')
        item.unit_purchase_price = purchase_price
        item.total_purchase_cost = purchase_price * item.quantity
        item.save(update_fields=['unit_purchase_price', 'total_purchase_cost'])


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='total_purchase_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(seed_sale_item_costs, migrations.RunPython.noop),
    ]
