# Generated by Django 5.2.8 on 2025-12-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=20, verbose_name='Report Type')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('total_sales', models.IntegerField(default=0, verbose_name='Total Sales')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Revenue')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Profit')),
                ('items_sold', models.JSONField(default=dict, verbose_name='Items Sold')),
                ('recipients', models.TextField(verbose_name='Recipients')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True, verbose_name='Success')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
            ],
            options={
                'verbose_name': 'Report Log',
                'verbose_name_plural': 'Report Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_recipients', models.TextField(blank=True, help_text='Emails séparés par des virgules', verbose_name='Email Recipients')),
                ('daily_enabled', models.BooleanField(default=True, verbose_name='Daily Report Enabled')),
                ('daily_time', models.TimeField(default='23:00', verbose_name='Daily Report Time')),
                ('weekly_enabled', models.BooleanField(default=True, verbose_name='Weekly Report Enabled')),
                ('weekly_time', models.TimeField(default='23:30', verbose_name='Weekly Report Time')),
                ('weekly_day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=6, verbose_name='Weekly Report Day')),
                ('monthly_enabled', models.BooleanField(default=True, verbose_name='Monthly Report Enabled')),
                ('monthly_time', models.TimeField(default='23:45', verbose_name='Monthly Report Time')),
                ('quarterly_enabled', models.BooleanField(default=True, verbose_name='Quarterly Report Enabled')),
                ('quarterly_time', models.TimeField(default='23:50', verbose_name='Quarterly Report Time')),
                ('yearly_enabled', models.BooleanField(default=True, verbose_name='Yearly Report Enabled')),
                ('yearly_time', models.TimeField(default='23:55', verbose_name='Yearly Report Time')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report Settings',
                'verbose_name_plural': 'Report Settings',
            },
        ),
    ]
