# Generated by Django 5.2.8 on 2025-12-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsettings',
            name='sender_email',
            field=models.EmailField(blank=True, help_text="Email utilisé pour l'envoi", max_length=254, verbose_name='Sender Email'),
        ),
        migrations.AddField(
            model_name='reportsettings',
            name='sender_password',
            field=models.CharField(blank=True, help_text="Mot de passe d'application ou SMTP", max_length=255, verbose_name='Sender Password'),
        ),
        migrations.AddField(
            model_name='reportsettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=255, verbose_name='SMTP Host'),
        ),
        migrations.AddField(
            model_name='reportsettings',
            name='smtp_port',
            field=models.IntegerField(default=587, verbose_name='SMTP Port'),
        ),
    ]
