# Generated by Django 5.2.8 on 2025-12-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Librairie Attaquaddoum', max_length=200, verbose_name='Store Name')),
                ('store_address', models.TextField(blank=True, verbose_name='Store Address')),
                ('store_phone', models.CharField(blank=True, max_length=20, verbose_name='Store Phone')),
                ('store_email', models.EmailField(blank=True, max_length=254, verbose_name='Store Email')),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Store Logo')),
                ('default_tva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Default VAT (%)')),
                ('currency', models.CharField(default='MAD', max_length=10, verbose_name='Currency')),
                ('currency_symbol', models.CharField(default='DH', max_length=5, verbose_name='Currency Symbol')),
                ('print_header', models.TextField(blank=True, verbose_name='Ticket Header')),
                ('print_footer', models.TextField(blank=True, verbose_name='Ticket Footer')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Settings',
                'verbose_name_plural': 'App Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('CASHIER', 'Vendeur')], default='CASHIER', max_length=10, verbose_name='Role'),
        ),
    ]
