# Generated by Django 5.2.8 on 2025-12-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appsettings_alter_user_options_user_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='cashier_can_manage_stock',
            field=models.BooleanField(default=False, verbose_name='Cashier can manage stock'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='cashier_can_view_stock',
            field=models.BooleanField(default=False, verbose_name='Cashier can view stock'),
        ),
    ]
