# Generated by Django 5.2.8 on 2025-12-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appsettings_cashier_can_manage_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_stock',
            field=models.BooleanField(default=False, verbose_name='Can manage stock'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_stock',
            field=models.BooleanField(default=False, verbose_name='Can view stock'),
        ),
    ]
