# Generated by Django 5.2.8 on 2025-12-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('PUSH', 'Local → Cloud'), ('PULL', 'Cloud → Local')], max_length=10, verbose_name='Sync Type')),
                ('records_synced', models.IntegerField(default=0, verbose_name='Records Synced')),
                ('success', models.BooleanField(default=True, verbose_name='Success')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
