# Generated by Codex on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_widen_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='company_cnss',
            field=models.CharField(blank=True, max_length=80, verbose_name='CNSS'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='company_ice',
            field=models.CharField(blank=True, max_length=80, verbose_name='ICE'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='company_if',
            field=models.CharField(blank=True, max_length=80, verbose_name='IF'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='company_patente',
            field=models.CharField(blank=True, max_length=80, verbose_name='Patente'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='company_rc',
            field=models.CharField(blank=True, max_length=80, verbose_name='RC'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='invoice_footer',
            field=models.TextField(blank=True, verbose_name='Invoice Footer'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='invoice_prefix',
            field=models.CharField(default='FAC', max_length=20, verbose_name='Invoice Prefix'),
        ),
    ]
